spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/to-da
    username: postgres
    password: postgres
    hikari:
      maximum-pool-size: 10
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
#        use_sql_comments: true
#logging:
#  level:
#    org:
#      hibernate:
#        type: trace