/*
 * This file is generated by jOOQ.
*/
package io.jedaev.dayon.model.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Task implements Serializable {

    private static final long serialVersionUID = 1221622557;

    private Long   id;
    private String text;

    public Task() {}

    public Task(Task value) {
        this.id = value.id;
        this.text = value.text;
    }

    public Task(
        Long   id,
        String text
    ) {
        this.id = id;
        this.text = text;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getText() {
        return this.text;
    }

    public void setText(String text) {
        this.text = text;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Task (");

        sb.append(id);
        sb.append(", ").append(text);

        sb.append(")");
        return sb.toString();
    }
}
