version: '2.0'
services:

#  redis:
#    image: redis
  db:
    image: postgres:12
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres


volumes:
  logvolume01: {}