version: '2.0'
services:

#  redis:
#    image: redis
  db:
    image: postgres:12
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
  idp:
    image: quay.io/keycloak/keycloak:11.0.2
    ports:
    - "9999:8080"
    restart: always
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin

volumes:
  logvolume01: {}