/*
 * This file is generated by jOOQ.
*/
package io.jedaev.dayon.model;


import io.jedaev.dayon.model.tables.Task;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in public
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.task</code>.
     */
    public static final Task TASK = io.jedaev.dayon.model.tables.Task.TASK;
}
